import {
    NFT_CCC,
    NFT_EXT_WITHOUT_APPROVE,
    NFT_ICNAMING,
    NFT_OGY_BUTTERFLY,
} from '@/canisters/nft/special';

export const ALL_COLLECTIONS = [
    // Tokens
    'ryjl3-tyaaa-aaaaa-aaaba-cai',
    'jwcfb-hyaaa-aaaaj-aac4q-cai',
    'ryjl3-tyaaa-aaaaa-aaaba-cai',
    'jwcfb-hyaaa-aaaaj-aac4q-cai',
    'irzpe-yqaaa-aaaah-abhfa-cai',
    'jwcfb-hyaaa-aaaaj-aac4q-cai',
    // prod
    'udtw4-baaaa-aaaah-abc3q-cai', // ? SHIKU_CANISTER_ID
    'qqamp-7iaaa-aaaah-qakha-cai', // ? POINT_CANISTER_ID
    'qnblj-lyaaa-aaaah-aa74a-cai', // ? ARTIST_ROUTER_CANISTER_ID
    '56www-tyaaa-aaaap-aai4q-cai', // ? NEW_RECORD_CANISTER_ID
    'od7d3-vaaaa-aaaap-aamfq-cai', // ? ORIGYN_yuku_CANISTER_ID
    'pzzyl-yyaaa-aaaah-adn6q-cai',
    'owefd-waaaa-aaaah-abu2q-cai', // ? CCC_PROXY_CANISTER_ID
    'pczmq-maaaa-aaaah-abhwa-cai', // ? LAUNCHPAD_CANISTER_ID
    'cxgiz-nyaaa-aaaah-abg6q-cai', // ? APPLY_CANISTER_ID
    'v43fl-cyaaa-aaaah-abc7a-cai', // ? OAT_CANISTER_ID
    '3j32q-6iaaa-aaaap-aaijq-cai', // ? LANDS_CANISTER_ID
    'rsyqn-haaaa-aaaah-adpsa-cai',
    // staging
    'pfsjt-fqaaa-aaaap-aaapq-cai', // ? SHIKU_CANISTER_ID
    'k52eo-fyaaa-aaaag-qagha-cai', // ? POINT_CANISTER_ID
    'st74o-biaaa-aaaah-abcoa-cai', // ? ARTIST_ROUTER_CANISTER_ID
    'd4uvm-2iaaa-aaaap-aakrq-cai', // ? NEW_RECORD_CANISTER_ID
    'owysw-uiaaa-aaaap-aamga-cai', // ? ORIGYN_yuku_CANISTER_ID
    'pm6jg-zqaaa-aaaah-adn5a-cai',
    'porhv-2iaaa-aaaap-aamca-cai', // ? CCC_PROXY_CANISTER_ID
    '4aatc-iyaaa-aaaao-aabsa-cai', // ? LAUNCHPAD_CANISTER_ID
    'cxgiz-nyaaa-aaaah-abg6q-cai', // ? APPLY_CANISTER_ID
    'xbgld-rqaaa-aaaah-abcqq-cai', // ? OAT_CANISTER_ID
    '3j32q-6iaaa-aaaap-aaijq-cai', // ? LANDS_CANISTER_ID
    'rsyqn-haaaa-aaaah-adpsa-cai',
    // test
    'ajy76-hiaaa-aaaah-aa3mq-cai', // ? SHIKU_CANISTER_ID
    'l2pzh-6iaaa-aaaah-abhpq-cai', // ? POINT_CANISTER_ID
    'v32d7-paaaa-aaaah-abc7q-cai', // ? ARTIST_ROUTER_CANISTER_ID
    'sgynd-aaaaa-aaaah-abcnq-cai', // ? NEW_RECORD_CANISTER_ID
    'patk5-byaaa-aaaap-aamda-cai', // ? ORIGYN_yuku_CANISTER_ID
    'pm6jg-zqaaa-aaaah-adn5a-cai',
    'tut64-gqaaa-aaaah-ab2qq-cai', // ? CCC_PROXY_CANISTER_ID
    'o2qzt-caaaa-aaaah-abhsa-cai', // ? LAUNCHPAD_CANISTER_ID
    'qhbz2-eiaaa-aaaah-abcaa-cai', // ? APPLY_CANISTER_ID
    'xlsz5-7aaaa-aaaah-abfma-cai', // ? OAT_CANISTER_ID
    'vpkok-7aaaa-aaaah-abjna-cai', // ? LANDS_CANISTER_ID
    'rsyqn-haaaa-aaaah-adpsa-cai',
    // NFT
    ...NFT_ICNAMING,
    ...NFT_CCC,
    ...NFT_EXT_WITHOUT_APPROVE,
    ...NFT_OGY_BUTTERFLY,
    // prod nft
    '4uzum-riaaa-aaaap-aai3q-cai',
    'xpegl-kaaaa-aaaah-abcrq-cai',
    'fx5d3-ayaaa-aaaap-aakgq-cai',
    'vnpdo-yqaaa-aaaah-adpla-cai',
    'j3az4-4aaaa-aaaah-abyhq-cai',
    'johir-5iaaa-aaaah-abyea-cai',
    'kbzc6-lyaaa-aaaap-abckq-cai',
    'gappj-raaaa-aaaap-aakoa-cai',
    'ke2v7-iqaaa-aaaap-aalda-cai',
    'uhabu-2aaaa-aaaah-adpma-cai',
    'shkzf-7iaaa-aaaah-addwq-cai',
    'dtopv-2yaaa-aaaah-admsq-cai',
    'j2zek-uqaaa-aaaal-acoxa-cai',
    'zicoj-2aaaa-aaaap-aaiea-cai',
    'bgi5q-eyaaa-aaaap-aak6q-cai',
    'swu4x-biaaa-aaaap-aaj3q-cai',
    'osona-biaaa-aaaap-aal3q-cai',
    'ajjxn-iiaaa-aaaah-adlga-cai',
    'utve7-eaaaa-aaaah-abouq-cai',
    'qdsos-7iaaa-aaaah-adpxq-cai',
    'ayvgq-riaaa-aaaap-abeoa-cai',
    'nncvb-tyaaa-aaaah-abh2q-cai',
    '52b2m-tyaaa-aaaai-qpbpa-cai',
    'cr2rc-vaaaa-aaaap-aakwa-cai',
    '27qc3-lyaaa-aaaap-aaimq-cai',
    '6je2e-caaaa-aaaap-aaiua-cai',
    'c7y4k-oqaaa-aaaap-aakxa-cai',
    'gkhkc-5yaaa-aaaah-abvoa-cai',
    'o7ehd-5qaaa-aaaah-qc2zq-cai',
    'nwyv2-gaaaa-aaaaj-arc2a-cai',
    'ut7hi-aiaaa-aaaap-aajnq-cai',
    'd26yv-eqaaa-aaaah-abz4q-cai',
    'seyiz-jqaaa-aaaah-abobq-cai',
    'zdxun-dyaaa-aaaap-aa3ma-cai',
    '33lzl-uyaaa-aaaap-aaxpa-cai',
    '335nj-syaaa-aaaap-aaikq-cai',
    'pkhyd-piaaa-aaaap-aal7q-cai',
    'nn6cu-rqaaa-aaaap-aa7ga-cai',
    'n5yqx-uqaaa-aaaap-aatja-cai',
    '53lcn-vyaaa-aaaah-ab4mq-cai',
    'uyk5m-zqaaa-aaaap-aa2fq-cai',
    'goncb-kqaaa-aaaap-aakpa-cai',
    'ah2fs-fqaaa-aaaak-aalya-cai',
    'q5fnf-jyaaa-aaaah-abwwa-cai',
    'v6rdg-paaaa-aaaap-aajka-cai',
    'fdcfh-2qaaa-aaaah-admha-cai',
    'afeuw-qaaaa-aaaap-aakya-cai',
    'ktlvk-giaaa-aaaap-aayja-cai',
    'fnzxe-niaaa-aaaap-aa6qq-cai',
    'zthsm-ayaaa-aaaap-aaigq-cai',
    '355dh-iiaaa-aaaap-aa46q-cai',
    'slzze-ciaaa-aaaah-aa7ra-cai',
    'pvimf-cyaaa-aaaah-abu4a-cai',
    '63ngu-eyaaa-aaaah-adfea-cai',
    '2zjt6-5aaaa-aaaah-adooa-cai',
    'ahos3-5yaaa-aaaah-abbna-cai',
    'drbbg-zaaaa-aaaap-aannq-cai',
    'qca2u-aaaaa-aaaah-abomq-cai',
    'ff3uc-miaaa-aaaap-aakfq-cai',
    'vsf7w-3aaaa-aaaap-aa2cq-cai',
    '5btbh-2aaaa-aaaap-aaqga-cai',
    '66orv-hqaaa-aaaah-acmnq-cai',
    'fab4i-diaaa-aaaah-acr2q-cai',
    'o4mai-2yaaa-aaaap-aal2q-cai',
    'xehin-vyaaa-aaaah-abo4a-cai',
    'unzmm-zyaaa-aaaap-abagq-cai',
    'l5lxn-5qaaa-aaaah-adnfa-cai',
    'e7jp7-aqaaa-aaaah-acr6a-cai',
    'gtiqk-kyaaa-aaaap-aa6zq-cai',
    '47moi-iqaaa-aaaap-aa3tq-cai',
    '6enz3-daaaa-aaaah-abxuq-cai',
    'fvsni-daaaa-aaaah-adlzq-cai',
    'gq7ji-saaaa-aaaap-aazeq-cai',
    '3hzxy-fyaaa-aaaap-aaiiq-cai',
    '2x763-hqaaa-aaaah-acupq-cai',
    'qqmo2-iyaaa-aaaap-aajwq-cai',
    '5lnqo-qyaaa-aaaah-abqdq-cai',
    '4wuoq-vqaaa-aaaah-acmbq-cai',
    'qekxn-6yaaa-aaaap-aa5bq-cai',
    'v5mzt-tqaaa-aaaah-abjoa-cai',
    '4roda-taaaa-aaaap-aa3sq-cai',
    '4pa74-jyaaa-aaaah-abqfq-cai',
    '6dm7p-oyaaa-aaaah-abxua-cai',
    'algz6-lqaaa-aaaap-aakza-cai',
    'ebkmf-xaaaa-aaaah-abs7a-cai',
    'tfitq-wqaaa-aaaap-aa2xq-cai',
    'fjz4q-6iaaa-aaaap-aagiq-cai',
    'n46fk-6qaaa-aaaai-ackxa-cai',
    'm7vrl-xaaaa-aaaap-aah3a-cai',
    'jouun-viaaa-aaaah-adnlq-cai',
    '2duyk-4yaaa-aaaap-aaioq-cai',
    '4ibzi-eaaaa-aaaah-abqfa-cai',
    'w3tmp-uiaaa-aaaap-aawea-cai',
    'vupsp-fyaaa-aaaah-abjpq-cai',
    '2wf5f-3qaaa-aaaap-aaxiq-cai',
    'twfpe-jaaaa-aaaah-abjza-cai',
    'tajq6-syaaa-aaaap-aaw3a-cai',
    'lovxf-kaaaa-aaaap-aalea-cai',
    'lt2gz-oaaaa-aaaah-abylq-cai',
    'hmz4w-fiaaa-aaaah-admlq-cai',
    'k6ucx-biaaa-aaaah-abyma-cai',
    'hc3r6-6yaaa-aaaah-admkq-cai',
    '2bcjs-tiaaa-aaaap-aa3ha-cai',
    'jezzy-xqaaa-aaaap-aaybq-cai',
    'svjgc-5yaaa-aaaah-abj7q-cai',
    'xizxk-fqaaa-aaaap-aa2nq-cai',
    '3j32q-6iaaa-aaaap-aaijq-cai',
    'kafas-uaaaa-aaaao-aaofq-cai',
    'wakh7-myaaa-aaaah-abo2a-cai',
    'xarx3-ayaaa-aaaah-abjbq-cai',
    'r6vtw-7iaaa-aaaap-aaoma-cai',
    'ml2cx-yqaaa-aaaah-qc2xq-cai',
    'fioai-paaaa-aaaap-aanzq-cai',
    'vqtoo-uqaaa-aaaap-aajla-cai',
    '7aawj-2aaaa-aaaah-abxsq-cai',
    'mfhqa-iyaaa-aaaai-abona-cai',
    'hz6n3-eaaaa-aaaah-admia-cai',
    'xkpgs-kaaaa-aaaap-aajea-cai',
    'szogo-byaaa-aaaah-adpyq-cai',
    'nkg3l-qaaaa-aaaah-adnqa-cai',
    'amrli-aiaaa-aaaap-aav4a-cai',
    's5eo5-gqaaa-aaaag-qa3za-cai',
    'ntmj5-jaaaa-aaaap-aamnq-cai',
    'jnosj-ayaaa-aaaap-abcaq-cai',
    'qv3zw-kqaaa-aaaap-aa27q-cai',
    'nusra-3iaaa-aaaah-qc2ta-cai',
    'pvu3q-aqaaa-aaaap-aamaq-cai',
    'eze6x-xiaaa-aaaap-aan4a-cai',
    'ft6xr-taaaa-aaaam-aafmq-cai',
    'vjadt-byaaa-aaaap-aa2aa-cai',
    'u44c2-mqaaa-aaaap-aa5ya-cai',
    'q6ods-tiaaa-aaaap-aajxq-cai',
    'daqp5-niaaa-aaaap-aaktq-cai',
    '73yov-xqaaa-aaaai-qpbcq-cai',
    '7hbq5-xyaaa-aaaah-abxsa-cai',
    'jx6g3-miaaa-aaaap-aamwa-cai',
    'gw7hg-iqaaa-aaaap-aanqq-cai',
    '3bag5-taaaa-aaaah-adoka-cai',
    'edzvd-wqaaa-aaaah-adl4q-cai',
    'aak4r-6aaaa-aaaah-adlhq-cai',
    'xd2zm-2iaaa-aaaap-aawaa-cai',
    'd5mc5-biaaa-aaaah-admtq-cai',
    'bjcsj-rqaaa-aaaah-qcxqq-cai',
    // staging nft
    'wt6ea-7aaaa-aaaah-adpca-cai',
    // test nft
    'kvgec-rqaaa-aaaah-acela-cai',
    '6ci7l-xqaaa-aaaah-adjkq-cai',
    'bxdf4-baaaa-aaaah-qaruq-cai',
    'ripyo-cqaaa-aaaah-abolq-cai',
    'jaffz-gyaaa-aaaah-abyfa-cai',
    'nusra-3iaaa-aaaah-qc2ta-cai',
    'vm5xi-hyaaa-aaaah-aboqa-cai',
    'yubtj-diaaa-aaaah-abxba-cai',
    'n2fbw-3aaaa-aaaah-ablva-cai',
    'wekml-7yaaa-aaaah-abwca-cai',
    'jye4c-myaaa-aaaah-adkva-cai',
    '5fzje-niaaa-aaaah-abpha-cai',
    '6qlam-vaaaa-aaaah-abddq-cai',
    '2moct-4iaaa-aaaah-adonq-cai',
    '72d6h-6qaaa-aaaah-acmlq-cai',
    'b6gpc-eqaaa-aaaah-abv5q-cai',
    'hmz4w-fiaaa-aaaah-admlq-cai',
    '6vpl4-7iaaa-aaaah-adffa-cai',
    'rgnvg-zaaaa-aaaah-abokq-cai',
    'ujnhf-3yaaa-aaaag-qcj6q-cai',
    'wt6ea-7aaaa-aaaah-adpca-cai',
    'vf64u-rqaaa-aaaah-aborq-cai',
    'q2elr-eaaaa-aaaah-abwwq-cai',
    'dtopv-2yaaa-aaaah-admsq-cai',
    'dhiaa-ryaaa-aaaae-qabva-cai',
    '3bag5-taaaa-aaaah-adoka-cai',
    '72bki-zqaaa-aaaah-adjoq-cai',
    'hipda-qiaaa-aaaah-adlwa-cai',
    'rw623-hyaaa-aaaah-qctcq-cai',
    'nsu6m-saaaa-aaaah-adkpq-cai',
    '5e75p-taaaa-aaaah-acu4q-cai',
    'u5xjx-7qaaa-aaaah-abovq-cai',
    '543mk-xaaaa-aaaah-acmgq-cai',
    'yzuhd-aaaaa-aaaah-abq5a-cai',
    'ole7w-yiaaa-aaaah-adkga-cai',
    'wozce-yiaaa-aaaah-ac6rq-cai',
    '77fby-tyaaa-aaaah-abpia-cai',
    'skjpp-haaaa-aaaae-qac7q-cai',
    'jjgof-qqaaa-aaaah-abyeq-cai',
    'bkf6l-4qaaa-aaaah-adlaq-cai',
    'upr6o-taaaa-aaaah-abowq-cai',
    'shkzf-7iaaa-aaaah-addwq-cai',
    'llf4i-riaaa-aaaag-qb4cq-cai',
    'fdcfh-2qaaa-aaaah-admha-cai',
    'kgv3m-liaaa-aaaah-adk4a-cai',
    '6migm-laaaa-aaaah-acmoq-cai',
    'szogo-byaaa-aaaah-adpyq-cai',
    '7rhmq-iiaaa-aaaah-abpja-cai',
    'b4gky-naaaa-aaaah-abzrq-cai',
    'bzsui-sqaaa-aaaah-qce2a-cai',
    'fvsni-daaaa-aaaah-adlzq-cai',
    's5eo5-gqaaa-aaaag-qa3za-cai',
    '2l7gd-5aaaa-aaaak-qcfvq-cai',
    '4scrg-aqaaa-aaaah-acl4a-cai',
    'zri47-daaaa-aaaah-adjzq-cai',
    'fab4i-diaaa-aaaah-acr2q-cai',
    'bzr5u-piaaa-aaaah-abkyq-cai',
    'vxyln-5aaaa-aaaah-abosq-cai',
    'pxij7-liaaa-aaaah-abyqa-cai',
    '7h4ue-aqaaa-aaaai-qpbaq-cai',
    'aoirz-fqaaa-aaaah-adlgq-cai',
    'bqeck-7aaaa-aaaah-abv4q-cai',
    '4pwl6-pyaaa-aaaah-abpaa-cai',
    'avnn4-7iaaa-aaaah-adlea-cai',
    'd26yv-eqaaa-aaaah-abz4q-cai',
    'telr2-5qaaa-aaaai-qiumq-cai',
    'wbytz-tqaaa-aaaah-adpba-cai',
    '3j32q-6iaaa-aaaap-aaijq-cai',
    'oeee4-qaaaa-aaaak-qaaeq-cai',
    'hc3r6-6yaaa-aaaah-admkq-cai',
    '7ubtp-faaaa-aaaah-acmkq-cai',
    'mo5a3-paaaa-aaaah-adstq-cai',
    '5eyb6-2aaaa-aaaah-ab3tq-cai',
    'a2laq-5qaaa-aaaah-abv3q-cai',
    'vnpdo-yqaaa-aaaah-adpla-cai',
    '6xpog-wyaaa-aaaah-adjja-cai',
    'pk6rk-6aaaa-aaaae-qaazq-cai',
    '5n3kc-miaaa-aaaah-ab3sa-cai',
    'b7cpg-5yaaa-aaaah-adlda-cai',
    '44a4o-3aaaa-aaaah-acl5a-cai',
    'jqs7j-myaaa-aaaah-aceaq-cai',
    'nf35t-jqaaa-aaaag-qbp4q-cai',
    '6xn2j-ryaaa-aaaah-acmma-cai',
    'nwyv2-gaaaa-aaaaj-arc2a-cai',
    'ysevz-xyaaa-aaaah-adj7a-cai',
    'o7ehd-5qaaa-aaaah-qc2zq-cai',
    '4ywdy-oaaaa-aaaah-acmaq-cai',
    'ie3wx-xyaaa-aaaah-adnmq-cai',
    'cbtii-2iaaa-aaaah-adlka-cai',
    '7mfck-baaaa-aaaah-acuqq-cai',
    'jouun-viaaa-aaaah-adnlq-cai',
    '2x763-hqaaa-aaaah-acupq-cai',
    '2szbe-kyaaa-aaaah-abxma-cai',
    'y5cyv-vaaaa-aaaah-abxaq-cai',
    'e7jp7-aqaaa-aaaah-acr6a-cai',
    'vupsp-fyaaa-aaaah-abjpq-cai',
    'ecujo-liaaa-aaaam-aafja-cai',
    'hgnoi-lyaaa-aaaah-adlxa-cai',
    'ml2cx-yqaaa-aaaah-qc2xq-cai',
    'vpkok-7aaaa-aaaah-abjna-cai',
    '7ndwb-7iaaa-aaaah-abpla-cai',
    'bjcsj-rqaaa-aaaah-qcxqq-cai',
    'uhabu-2aaaa-aaaah-adpma-cai',
    'aak4r-6aaaa-aaaah-adlhq-cai',
    'ubttg-iqaaa-aaaah-aboxq-cai',
    '7ghew-jqaaa-aaaah-acmjq-cai',
    'qdsos-7iaaa-aaaah-adpxq-cai',
    'gkhkc-5yaaa-aaaah-abvoa-cai',
    'nkg3l-qaaaa-aaaah-adnqa-cai',
    'f7vdk-fqaaa-aaaah-abzkq-cai',
    'aujny-gaaaa-aaaah-abv2q-cai',
    '63ngu-eyaaa-aaaah-adfea-cai',
    '3rvic-6aaaa-aaaah-abxkq-cai',
    'hx4at-7qaaa-aaaah-admja-cai',
    'f3qaa-yqaaa-aaaah-adlyq-cai',
    '7h4ue-aqaaa-aaaai-qpbaq-cai',
    'xzxhy-oiaaa-aaaah-qclnq-cai',
    'pk6rk-6aaaa-aaaae-qaazq-cai',
    'bzsui-sqaaa-aaaah-qce2a-cai',
    'dhiaa-ryaaa-aaaae-qabva-cai',
    'skjpp-haaaa-aaaae-qac7q-cai',
    'rw623-hyaaa-aaaah-qctcq-cai',
    'bxdf4-baaaa-aaaah-qaruq-cai',
    '3mttv-dqaaa-aaaah-qcn6q-cai',
    'lix2q-6yaaa-aaaal-qdbaa-cai',
    '5izaq-vyaaa-aaaah-qcz4a-cai',
    'llf4i-riaaa-aaaag-qb4cq-cai',
    'nf35t-jqaaa-aaaag-qbp4q-cai',
    's36wu-5qaaa-aaaah-qcyzq-cai',
    'cchps-gaaaa-aaaak-qasaa-cai',
];
